using System;
using System.Globalization;
using System.IO;

/// <summary>
/// Loads the reference fixtures generated by the Python onnxruntime pipeline.
/// Paths resolve inside the Unity project by default and can be overridden
/// with the CV_FIXTURES environment variable for out-of-editor runs.
/// </summary>
public static class CvFixtures
{
    public static string Root
    {
        get
        {
            string overridePath = Environment.GetEnvironmentVariable("CV_FIXTURES");
            if (!string.IsNullOrEmpty(overridePath))
            {
                return overridePath;
            }

            return Path.Combine("Assets", "Tests", "Fixtures");
        }
    }

    public static void LoadYoloxRows(out int[] rowIndices, out float[] rowValues)
    {
        byte[] bytes = File.ReadAllBytes(Path.Combine(Root, "yolox_bus_rows.bin"));
        int rowCount = BitConverter.ToInt32(bytes, 0);
        int valuesPerRow = BitConverter.ToInt32(bytes, 4);
        rowIndices = new int[rowCount];
        rowValues = new float[rowCount * valuesPerRow];
        int offset = 8;
        for (int row = 0; row < rowCount; row++)
        {
            rowIndices[row] = BitConverter.ToInt32(bytes, offset);
            offset += 4;
            for (int v = 0; v < valuesPerRow; v++)
            {
                rowValues[row * valuesPerRow + v] = BitConverter.ToSingle(bytes, offset);
                offset += 4;
            }
        }
    }

    public sealed class ExpectedDetections
    {
        public int InputSize;
        public float Scale;
        public int SourceWidth;
        public int SourceHeight;
        public float ScoreThreshold;
        public float IouThreshold;
        public Detection[] Detections;
    }

    public static ExpectedDetections LoadYoloxExpected()
    {
        string[] lines = File.ReadAllLines(Path.Combine(Root, "yolox_bus_expected.txt"));
        string[] header = lines[0].Split(' ');
        ExpectedDetections expected = new ExpectedDetections
        {
            InputSize = int.Parse(header[0], CultureInfo.InvariantCulture),
            Scale = float.Parse(header[1], CultureInfo.InvariantCulture),
            SourceWidth = int.Parse(header[2], CultureInfo.InvariantCulture),
            SourceHeight = int.Parse(header[3], CultureInfo.InvariantCulture),
            ScoreThreshold = float.Parse(header[4], CultureInfo.InvariantCulture),
            IouThreshold = float.Parse(header[5], CultureInfo.InvariantCulture),
            Detections = new Detection[lines.Length - 1]
        };
        for (int i = 1; i < lines.Length; i++)
        {
            string[] parts = lines[i].Split(' ');
            expected.Detections[i - 1] = new Detection(
                int.Parse(parts[0], CultureInfo.InvariantCulture),
                float.Parse(parts[1], CultureInfo.InvariantCulture),
                float.Parse(parts[2], CultureInfo.InvariantCulture),
                float.Parse(parts[3], CultureInfo.InvariantCulture),
                float.Parse(parts[4], CultureInfo.InvariantCulture),
                float.Parse(parts[5], CultureInfo.InvariantCulture));
        }

        return expected;
    }

    public static byte[] LoadClassMap(out int width, out int height)
    {
        string[] lines = File.ReadAllLines(Path.Combine(Root, "fastscnn_bus_classmap.txt"));
        string[] header = lines[0].Split(' ');
        width = int.Parse(header[0], CultureInfo.InvariantCulture);
        height = int.Parse(header[1], CultureInfo.InvariantCulture);
        string[] runs = lines[1].Split(' ');
        byte[] map = new byte[width * height];
        int cursor = 0;
        for (int i = 0; i < runs.Length; i += 2)
        {
            byte value = byte.Parse(runs[i], CultureInfo.InvariantCulture);
            int length = int.Parse(runs[i + 1], CultureInfo.InvariantCulture);
            for (int k = 0; k < length; k++)
            {
                map[cursor++] = value;
            }
        }

        if (cursor != map.Length)
        {
            throw new InvalidDataException("Class map RLE did not fill the expected area.");
        }

        return map;
    }
}
